package com.keysoft.pigfarm.integration.sap;

import java.util.List;

import org.springframework.boot.jackson.JsonComponent;

import com.fasterxml.jackson.annotation.JsonProperty;

import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Generated by Speed Generator
 * 
 * @author <a href="mailto:ngtrungkien@gmail.com">Kien Nguyen</a>
 */
@Data
@NoArgsConstructor
@JsonComponent
public class BarnPlanJson {
	@JsonProperty("item")
	List<BarnPlanDetailJson> barnPlans;
}