package com.keysoft.pigfarm.common;

public enum MapKeyExportEnum {
	TO_STOCK_NAME("TO_STOCK_NAME"),
	TO_STOCK_ADDRESS("TO_STOCK_ADDRESS"),
	VENDOR("VENDOR"),
	PO_CODE("PO_CODE"),
	DO_CODE("DO_CODE"),
	CUSTOMER_NAME("CUSTOMER_NAME"),
	FROM_STOCK_NAME("FROM_STOCK_NAME"),
	FROM_STOCK_ADDRESS("FROM_STOCK_ADDRESS"),
	LICENSE_PLATE("LICENSE_PLATE"),
	MOVEMENT_TYPE("MOVEMENT_TYPE"),
	DAY("DAY"),
	MONTH("MONTH"),
	YEAR("YEAR"),
	
	MATERIAL_NO("NO"),
	MATERIAL_CODE("CODE"),
	MATERIAL_NAME("NAME"),
	MATERIAL_BATCH("BATCH"),
	MATERIAL_UNIT("UNIT"),
	MATERIAL_QUANTITY("QUANTITY"),
	MATERIAL_WEIGHT("WEIGHT"),
	MATERIAL_NOTE("NOTE"),
	MATERIAL_REQ_QUANTITY("REQ_QUANTITY"),
	MATERIAL_REQ_WEIGHT("REQ_WEIGHT"),
	
	
	TOTAL_REQ_QUANTITY("TOTAL_REQ_QUANTITY"),
	TOTAL_QUANTITY("TOTAL_QUANTITY"),
	TOTAL_REQ_WEIGHT("TOTAL_REQ_WEIGHT"),
	TOTAL_WEIGHT("TOTAL_WEIGHT"),
	
	TOTAL_AMOUNT("tongSoLuong"),
	TOTAL_WEIGH("tongKhoiLuong"),
	TOTAL_GIAMTRU("tongGiamTru"),
	TOTAL_HEOCAI("tongSLHeoCai")
	;

	public String key;

	private MapKeyExportEnum(String key) {
		this.key = key;
	}
}
