package com.keysoft.pigfarm.production.dto;

import java.time.LocalDateTime;

import com.keysoft.pigfarm.common.BaseDto;

import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.experimental.SuperBuilder;

/**
 * Generated by Speed Generator
 * 
 * @author <a href="mailto:ngtrungkien@gmail.com">Kien Nguyen</a>
 */
@Data
@SuperBuilder
@NoArgsConstructor
@EqualsAndHashCode(callSuper = false)
public class FinishedProductDto extends BaseDto{
  	private Long id;
  	private String pigIdentifier;
  	private String processOrderCode;
  	private String stockCode;
  	private String transCode;
  	private java.math.BigDecimal quantity;
  	private java.math.BigDecimal volumn;
  	private String batch;
  	private String createdBy;
  	private LocalDateTime createdDate;
  	private String modifiedBy;
  	private LocalDateTime modifiedDate;
}