package com.keysoft.pigfarm.production.dto;

import java.math.BigDecimal;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.keysoft.pigfarm.common.BaseDto;

import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.experimental.SuperBuilder;

/**
 * Generated by Speed Generator
 * 
 * @author <a href="mailto:ngtrungkien@gmail.com">Kien Nguyen</a>
 */
@Data
@SuperBuilder
@NoArgsConstructor
@EqualsAndHashCode(callSuper = false)
@JsonInclude(JsonInclude.Include.NON_NULL)
public class MaterialDto extends BaseDto{
  	private Long id;
  	private String code;
  	private String name;
  	private String groupCode;
  	private String groupName;
  	private String unit;
  	private String batch;
  	private String purchasingGroup;
  	private String industryStandardDescription;
  	private String status;
  	
  	private String unsignedName;
  	private String stockCode;
  	private Map<String, Object> unitConversion;
  	private List<UnitConversionDto> unitConversions;
  	private String description;
  	
  	private String suggestName;
  	private String fastCode;
  	private boolean selected;
  	
  	private BigDecimal quantity;
 	private String orderUnit;
	private String expiredDate;
	private String deliveryDate;
	private String manufacturedDate;
	private String pigType;
	private String type;
	private BigDecimal weight;
	private String reason;
	private String note;
	private BigDecimal actuallyImported;
	private BigDecimal actuallyExported;
	private BigDecimal retained;	
	private BigDecimal expectedQuantity;
	private String rowId;
	private String itemNum;
	private BigDecimal grossWeight;
	private String weightUnit;
	private boolean requiredBatch;
	private BigDecimal totalRetainedQuantity;
	
	private Integer postingDay;
	private Map<Integer, String> actuallyExporteds;
	private String keyword;
	
	private Set<String> units;
	private Set<String> batchs;
}