package com.keysoft.pigfarm.production.dto;

import java.math.BigDecimal;
import java.time.LocalDateTime;

import com.keysoft.pigfarm.common.BaseDto;

import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.experimental.SuperBuilder;

/**
 * Generated by Speed Generator
 * 
 * @author <a href="mailto:ngtrungkien@gmail.com">Kien Nguyen</a>
 */
@Data
@SuperBuilder
@NoArgsConstructor
@EqualsAndHashCode(callSuper = false)
public class OtherCostDto extends BaseDto {
  	private Long id;
  	private String type;
  	private BigDecimal cost;
  	private String unit;
  	private Integer month;
  	private Integer year;
  	private LocalDateTime recordDate;
  	private String consumingDate;
  	private FarmDto farm;
  	private String username;
  	private String farmName;
  	private String transCode;
}