package com.keysoft.pigfarm.integration.mobile;

import java.math.BigDecimal;

import com.fasterxml.jackson.annotation.JsonProperty;

import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Generated by Speed Generator
 * 
 * @author <a href="mailto:ngtrungkien@gmail.com">Kien Nguyen</a>
 */
@Data
@NoArgsConstructor
public class OtherCostJson {
	@JsonProperty("farmCode")
  	private String farmCode;
	
	@JsonProperty("type")
  	private String type;
	
	@JsonProperty("cost")
  	private BigDecimal cost;
	
	@JsonProperty("unit")
  	private String unit;
	
	@JsonProperty("month")
  	private Integer month;
	
	@JsonProperty("year")
  	private Integer year;
	
	@JsonProperty("recordDate")
  	private String recordDate;
	
	@JsonProperty("transCode")
  	private String transCode;
}