package com.keysoft.pigfarm.production.dto;

import java.time.LocalDate;

import lombok.Data;

/**
 * Generated by Speed Generator
 * 
 * @author <a href="mailto:ngtrungkien@gmail.com">Kien Nguyen</a>
 */
@Data
public class PigReleaseDto {
  	private Long id;
  	private String pigIdentifier;
  	private String processOrderCode;
  	private LocalDate releaseDate;
  	private java.math.BigDecimal quantity;
  	private java.math.BigDecimal releaseVolumnTotal;
  	private java.math.BigDecimal averageVolumn;
  	private java.math.BigDecimal releaseWeight;
  	private String depotCode;
}