package com.keysoft.pigfarm.master.dto;

import java.util.ArrayList;
import java.util.List;

import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.experimental.SuperBuilder;

/**
 * Generated by Speed Generator
 * 
 * @author <a href="mailto:ngtrungkien@gmail.com">Kien Nguyen</a>
 */
@Data
@SuperBuilder
@NoArgsConstructor
@EqualsAndHashCode
public class GroupDto {
  private String id;
  private String name;
  private boolean enabled;
  private Integer systemGroup;
  private List<String> roleIds = new ArrayList<>();
  private List<String> roleNames = new ArrayList<>();
  
  private List<UserDto> appUsers;
  private List<RoleDto> roles;
}