package com.keysoft.pigfarm.production.dto;
import com.keysoft.pigfarm.common.BaseDto;

import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.experimental.SuperBuilder;

/**
 * Generated by Speed Generator
 * 
 * @author <a href="mailto:ngtrungkien@gmail.com">Kien Nguyen</a>
 */
@Data
@SuperBuilder
@NoArgsConstructor
@EqualsAndHashCode(callSuper = false)
public class BarnDto extends BaseDto {
  	private Long id;
  	private String code;
  	private String name;
  	private String wbsId;
  	private String wbsCode;
  	private String wbsDesc;
  	private FarmDto farm;
  	private String status;
  	
  	private String farmCode;
  	private String username ;
  	private Integer totalPigRetained ;
  	private Integer totalPigDead;
}