package com.keysoft.pigfarm.production.dto;

import lombok.Data;

/**
 * Generated by Speed Generator
 * 
 * @author <a href="mailto:ngtrungkien@gmail.com">Kien Nguyen</a>
 */
@Data
public class StockDto {
  	private Long id;
  	private String code;
  	private String name;
  	private String type;
  	private FarmDto farm;
}