package com.keysoft.pigfarm.production.dto;

import java.time.LocalDate;
import java.time.format.DateTimeFormatter;

import com.keysoft.pigfarm.common.BaseDto;

import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.experimental.SuperBuilder;

/**
 * Generated by Speed Generator
 * 
 * @author <a href="mailto:ngtrungkien@gmail.com">Kien Nguyen</a>
 */

@Data
@SuperBuilder
@NoArgsConstructor
@EqualsAndHashCode(callSuper = false)
public class PigEntryDto extends BaseDto{
  	private Long id;
  	private String pigIdentifier;
  	private String processOrderCode;
  	private LocalDate entryDate;
  	private LocalDate matureDate;
  	private String sourceFarm;
  	private String receiveFarm;
  	private Integer quantity;
  	private java.math.BigDecimal totalEntryVolumn;
  	private java.math.BigDecimal averageVolume;
  	private Integer ageWeek;
  	private LocalDate fromDate;
  	private LocalDate toDate;
  	private String transCode;
  	private String materialCode;
  	private String materialBatch;
  	private String status;
  	private Integer totalPig;
  	private String username;
  	
	private String sourceFarmName;
  	private String receiveFarmName;
  	
  	private String entryDateStr;
  	private String displayEntryDate;
  	public String getDisplayEntryDate() {
  		if (entryDate != null) {
  			return DateTimeFormatter.ofPattern("dd-MM-yyyy").format(entryDate); 
  		} else {
  			return null;
  		}
  	}  	
  	private String displayMatureDate;
  	public String getDisplayMatureDate() {
  		if (matureDate != null) {
  			return DateTimeFormatter.ofPattern("dd-MM-yyyy").format(matureDate); 
  		} else {
  			return null;
  		}
  	}
}