package com.keysoft.pigfarm.master.dto;

import java.util.List;

import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Generated by Speed Generator
 * 
 * @author <a href="mailto:ngtrungkien@gmail.com">Kien Nguyen</a>
 */
@Data
@NoArgsConstructor
public class RoleDto {
  private String id;
  private String name;
  private String description;
  private boolean selected;
  private String type;
  
  public RoleDto(String name, String description) {
	super();
	this.name = name;
	this.description = description;
}
private List<GroupDto> appGroups;
  private List<UserDto> appUsers;
}