package com.keysoft.pigfarm.master.dto;

import java.time.LocalDate;
import java.util.List;

import com.keysoft.pigfarm.common.BaseDto;
import com.keysoft.pigfarm.production.dto.FarmDto;
import com.keysoft.pigfarm.production.dto.PlantDto;

import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.experimental.SuperBuilder;

/**
 * Generated by Speed Generator
 * 
 * @author <a href="mailto:ngtrungkien@gmail.com">Kien Nguyen</a>
 */
@Data
@SuperBuilder
@NoArgsConstructor
@EqualsAndHashCode(callSuper = false)
public class UserDto extends BaseDto {
  private String id;
  private boolean accountExpired;
  private boolean accountLocked;
  private boolean credentialsExpired;
  private boolean accountEnabled;
  private String username;
  private String password;
  private String firstName;
  private String lastName;
  private String email;
  private Integer version;
  private Integer userLevel;
  private String createdBy;
  private LocalDate createdDate;
  private String modifiedBy;
  private LocalDate modifiedDate;
  private LocalDate passwordChangedDate;
  private String referCode;
  private List<GroupDto> appGroups;
  private List<RoleDto> roles;
  private String confirmPassword;
  private Long groupId;
  private List<String> groupIds;
  private String groupName;
  private List<Long> roleIds;
  private boolean check;
  
  private List<PlantDto> plants;
  private List<String> plantCodes;
  private List<FarmDto> farms;
  private List<String> farmCodes;
  
  private String selectedFarmCodes;
  private String mailToReport;
  
}