package com.keysoft.pigfarm.master.dto;

import lombok.Data;
import lombok.Builder;

/**
 * Generated by Speed Generator
 * 
 * @author <a href="mailto:ngtrungkien@gmail.com">Kien Nguyen</a>
 */
@Data
public class FieldTypeDto {
  	private Long id;
  	private String name;
}