package com.keysoft.pigfarm.production.dto;

import java.util.List;

import com.keysoft.pigfarm.common.BaseDto;

import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.experimental.SuperBuilder;

/**
 * Generated by Speed Generator
 * 
 * @author <a href="mailto:ngtrungkien@gmail.com">Kien Nguyen</a>
 */
@Data
@SuperBuilder
@NoArgsConstructor
@EqualsAndHashCode(callSuper = false)
public class SystemParameterDto extends BaseDto{
  private Long id;
  private String paramName;
  private String paramValue;
  private String description;
  private Integer version;
  
  //get material
  private List<String> paramNames;
  private String username;
}