package com.keysoft.pigfarm.production.dto;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;

import com.keysoft.pigfarm.common.BaseDto;
import com.keysoft.pigfarm.common.DatePatternEnum;

import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.experimental.SuperBuilder;

/**
 * Generated by Speed Generator
 * 
 * @author <a href="mailto:ngtrungkien@gmail.com">Kien Nguyen</a>
 */
@Data
@SuperBuilder
@NoArgsConstructor
@EqualsAndHashCode(callSuper = false)
public class BarnPlanDto extends BaseDto {
	private Long id;
  	private String barnCode ;
  	private String transCode ;
  	private LocalDate barnEmptyDate;
  	private LocalDate realBarnEmptyDate;
  	private String pigType ;
  	private Integer barnVolumn;
  	private Integer realBarnVolumn;
  	private String status;
  	private String createdBy;
  	private LocalDateTime createdDate;
  	private String modifiedBy;
  	private LocalDateTime modifiedDate;
  	private BarnDto barn;
  	
  	// for searching
  	private String username;
  	private String farmCode;
  	private String farmName;
  	private String barnEmptyDateSearchPeriod;
  	private LocalDate startBarnEmptyDateSearch;
  	private LocalDate endBarnEmptyDateSearch;
	private String searchFromDate;
	private String searchToDate;
  	
  	// for display
	private String barnEmptyDateDisplay;
  	private String realBarnEmptyDateDisplay;
  	public String getBarnEmptyDateDisplay() {
  		if (barnEmptyDate != null) {
  			return DateTimeFormatter.ofPattern(DatePatternEnum.DD_MM_YYYY_2.pattern).format(barnEmptyDate);	
  		}
  		return "";
  	}
  	public String getRealBarnEmptyDateDisplay() {
  		if (realBarnEmptyDate != null) {
  			return DateTimeFormatter.ofPattern(DatePatternEnum.DD_MM_YYYY_2.pattern).format(realBarnEmptyDate);	
  		}
  		return "";
  	}
  	
  	
  	
}