package com.keysoft.pigfarm.weighing.dto;

import lombok.Data;

/**
 * Generated by Speed Generator
 * 
 * @author <a href="mailto:ngtrungkien@gmail.com">Kien Nguyen</a>
 */
@Data
public class KhachHangDto {
  	private Long id;
  	private Integer sttkh;
  	private String maKh;
  	private String tenKh;
  	private String diaChi;
  	private String dienThoai;
}