package com.keysoft.pigfarm.production.dto;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;

import com.keysoft.pigfarm.common.BaseDto;

import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.experimental.SuperBuilder;

/**
 * Generated by Speed Generator
 * 
 * @author <a href="mailto:ngtrungkien@gmail.com">Kien Nguyen</a>
 */
@Data
@SuperBuilder
@NoArgsConstructor
@EqualsAndHashCode(callSuper = false)
public class PlanDto extends BaseDto {
  	private Long id;
  	private String pigIdentifier;
  	private String barnCode;
  	private String pigType;
  	private String location;
  	private LocalDate expectedDate;
  	private Integer quantity;
  	private String status;
  	private LocalDateTime createdDate;
  	private LocalDate DisplayExpectedDate;
  	private LocalDate DisplayCreatedDate;
      public String getDisplayExpectedDate() {
    	  if (expectedDate != null) {
    		  return DateTimeFormatter.ofPattern("dd-MM-yyyy").format(expectedDate);  
    	  } else {
    		  return null;
    	  }
      }
      public String getDisplayCreatedDate() {
    	  if (createdDate != null) {
    		  return DateTimeFormatter.ofPattern("dd-MM-yyyy").format(createdDate);  
    	  } else {
    		  return null;
    	  }
      }
}