package com.keysoft.pigfarm.weighing.dto;

import java.time.LocalDateTime;
import java.util.List;

import com.keysoft.pigfarm.common.BaseDto;

import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.experimental.SuperBuilder;

/**
 * Generated by Speed Generator
 * 
 * @author <a href="mailto:ngtrungkien@gmail.com">Kien Nguyen</a>
 */
/**
 * Bang phieu can
 */
@Data
@SuperBuilder
@NoArgsConstructor
@EqualsAndHashCode(callSuper = false)
public class PhieuCanDto extends BaseDto {
  	private Long id;
  	private String soPhieu;
  	private Integer soPhieuNum;
  	private LocalDateTime ngayBd;
  	private String soPhieuXk;
  	private String tenKh;
  	private String diaChi;
  	private String soXe;
  	private String chuong;
  	private String nhanVien;
  	private String traiXuat;
  	private String capNhat;
  	private String ghiChu;
  	private List<PhieuCanChiTietDto> phieuCanChiTiets;
}