package com.keysoft.pigfarm.weighing.dto;

import java.time.LocalDateTime;

import lombok.Data;

/**
 * Generated by Speed Generator
 * 
 * @author <a href="mailto:ngtrungkien@gmail.com">Kien Nguyen</a>
 */
/**
 * Bang phieu can chi tiet
 */
@Data
public class PhieuCanChiTietDto {
  	private Long id;
  	private Integer lanCan;
  	private String loaiHang;
  	private Integer soLuong;
  	private Integer tlCan;
  	private Integer slHeoCai;
  	private String trangThai;
  	private Integer tlGiamTru;
  	private String ghiChu;
  	private LocalDateTime ngay;
  	private String dvt;
  	private String traiXuat;
  	private String soPhieu;
  	private String soPhieuXk;
  	private String capNhat;
  	private String xoaPhieu;
  	private String chuong;
  	
  	private PhieuCanDto phieuCan;
  	private String ngayCan;
  	private String tenChuong;
}