package com.keysoft.pigfarm.production.dto;

import java.time.LocalDate;
import java.time.LocalDateTime;

import lombok.Data;

/**
 * Generated by Speed Generator
 * 
 * @author <a href="mailto:ngtrungkien@gmail.com">Kien Nguyen</a>
 */
@Data
public class PigDto {
  	private Long id;
  	private String identifier;
  	private String batch;
  	private String pigGroup;
  	private String earTag;
  	private LocalDate birthDate;
  	private String type;
  	private Integer quantity;
  	private String createdBy;
  	private LocalDateTime createdDate;
  	private String modifiedBy;
  	private LocalDateTime modifiedDate;
}