package com.keysoft.pigfarm.controller;

import java.util.Locale;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.validation.Valid;

import org.springframework.stereotype.Controller;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.servlet.ModelAndView;

import com.keysoft.pigfarm.production.dto.StockDto;

import lombok.extern.slf4j.Slf4j;

/**
 * Generated by Speed Generator
 * 
 * @author <a href="mailto:ngtrungkien@gmail.com">Kien Nguyen</a>
 */
 @Slf4j
@Controller
public class StockController extends BaseController {

    @GetMapping("/stock/list")
    public ModelAndView list(HttpServletRequest request) throws Exception {
    	log.debug("entering 'list' method...");

        //modelAndView.addObject("stocks", stockManager.gets());

        return new ModelAndView("stock-list");
    }
    
    @PostMapping("/stock/list")
    public ModelAndView search(@Valid StockDto criteria, BindingResult bindingResult){
    	log.debug("entering 'search' method...");
		ModelAndView modelAndView = new ModelAndView("stock-list");
		//modelAndView.addObject("page", stockManager.gets(criteria));
		modelAndView.addObject("criteria", criteria);
        return modelAndView;
    }
    
    @ModelAttribute
    @GetMapping("/stock/form")
    public ModelAndView show(@RequestParam (value="id", required=false) Long id) throws Exception {
    	log.debug("entering 'show' method...");
    
    	ModelAndView modelAndView = new ModelAndView("stock-form");
        //modelAndView.addObject(stockManager.get(id));

		modelAndView.addObject("stock", new StockDto());

        return modelAndView;
    }

    @PostMapping("/stock/save")
    public String save(StockDto stockDto, BindingResult bindingResult, HttpServletRequest request, HttpServletResponse response) throws Exception {
        log.debug("entering 'save' method...");

        Locale locale = request.getLocale();
        String view = "stock-form";
        
        if (bindingResult.hasErrors()) {
        	addError(request, bindingResult.getAllErrors().toString());
            return view;
        }

        //stockManager.save(stockDto);
        addMessage(request, getText("stock.updated", locale));
        view = "redirect:/stock/list";

        return view;
    }
    
}