package com.keysoft.pigfarm.integration.sap;

public enum MapKeyApiEnum {
	MATERIALS("MATERIALS"),
	// export key
	CODE("CODE"),
	MESSAGE("MESSAGE"),
	
	// purchase requisition key
	ZFM_PRFSHOPFLOOR_IF("ZFM_PRFSHOPFLOOR_IF"),
	TRANS_CODE("TRANSCODE"),
	PR_GROUP_CODE("PRGROUPCODE"),
	PR_TYPE("PRTYPE"),
	PLANT("PLANT"),
	REQUISITIONER("REQUISITIONER"),
	ROW_ID("rowid"),
	FARM_CODE("FARMCODE"),
	STOCK_CODE("STOCKCODE"),
	
	// goods issue key
	CUSTOMER("CUSTOMER"),
	DO_CODE("DOCODE"),
	POSTING_DATE("POSTINGDATE"),
	COST_CENTER("COSTCENTER"),
	REASON("REASON"),
	MOVEMENT_TYPE("MOVEMENTTYPE"),
	
	// goods receipt key
	PO_CODE("POCODE"),
	PR_CODE("PRCODE"),
	
	// material key
	MATERIAL_CODE("CODE"),
	MATERIAL_NAME("NAME"),
	MATERIAL_GROUP_CODE("GROUPCODE"),
	MATERIAL_GROUP_NAME("GROUPNAME"),
	MATERIAL_QUANTITY("QUANTITY"),
	MATERIAL_UNIT("UNIT"),
	MATERIAL_ORDER_UNIT("ORDERUNIT"),
	MATERIAL_BATCH("BATCH"),
	MATERIAL_NOTE("NOTE"),
	MATERIAL_ITEMTEXT("ITEMTEXT"),
	MATERIAL_DELIVERY_DATE("DELIVERYDATE"),
	MATERIAL_EXPIRED_DATE("EXPIREDDATE"),
	MATERIAL_MANUFACTURED_DATE("MANUFACTUREDDATE"),
	MATERIAL_STORAGE_TYPE("STORAGETYPE"),
	MATERIAL_ITEM_NUM("ITEMNUM"),
	MATERIAL_GROSS_WEIGHT("GROSSWEIGHT"),
	MATERIAL_WEIGHT_UNIT("WEIGHTUNIT"),
	MATERIAL_TOTAL_RETAINED("TOTAL_RETAINED"),
	MATERIAL_AMOUNT_EARLY_STAGE("AMOUNT_EARLY_STAGE"),
	MATERIAL_AMOUNT_FINAL_STAGE("AMOUNT_FINAL_STAGE"),
	MATERIAL_AMOUNT_GOODSRECEIPT("AMOUNT_GOODSRECEIPT"),
	MATERIAL_AMOUNT_GOODSISSUE("AMOUNT_GOODSISSUE"),
	
	
	//Goods Attrition key
	PROCESS_ORDER_CODE("PROCESSORDERCODE"),
	ZFM_XTHFSHOPFLOOR_IF("ZFM_XTHFSHOPFLOOR_IF"),
	CREATED_BY("CREATEDBY"),
	INSERT("INSERT"),
	GA_TYPE("ISSUE_TYPE"), //F la trai heo thit, S la trai heo giong nai.
	
	//barn plan key
	ZFM_PP_8006("ZFM_PP_8006"),
	ITEMS("ITEMS"),
	BARN_CODE("BARNCODE"),
	BARN_EMPTY_DATE("BARNEMPTYDATE"),
	PIG_TYPE("PIGTYPE"),
	BARN_VOLUMN("BARNVOLUMN"),
	
	// process order key
	ZFM_PP8014("ZFM_PP8014"),
	START_DATE("STARTDATE"),
	END_DATE("ENDDATE"),
	QUANTITY("QUANTITY"),
	
	//closed process order key
	ZFM_PP_8024("ZFM_PP_8024"),
	FINCONF("FINCONF"),
	FINCONF_VALUE("X"),
	DATE("DATE"),
	
	// goods issue, goods receipt
	ZFM_GIGRFSHOPFLOOR_IF("ZFM_GIGRFSHOPFLOOR_IF"),
	TRANS_TYPE("TRANSTYPE"),
	DELETE("DELETE"),
	LICENSE_PLATE("BSX"),
	PLANT_GI("PLANTI"),
	FARM_CODE_GI("FARMCODEI"),
	PLANT_GR("PLANTR"),
	FARM_CODE_GR("FARMCODER"),
	
	// finish production
	ZFM_NTPFSHOPFLOOR_IF("ZFM_NTPFSHOPFLOOR_IF"),
	
	// general ledger
	ZFM_GLAPP_IF("ZFM_GLAPP_IF"),
	DOC_CODE_GL("DOC_CODE"),
	DOC_SYMBOL_GL("DOC_SYMBOL"),
	DOC_DATE_GL("DOC_DATE"),
	DOC_NUM_GL("DOC_NUM"),
	APP("APP"),
	AMOUNT("AMOUNT"),
	VENDOR_CODE("VENDOR_CODE"),
	VENDOR_NAME("VENDOR_NAME"),
	VENDOR_TAX("VENDOR_TAX"),
	VENDOR_ADD("VENDOR_ADDRESS"),
	DESCRIPTION("DESCRIPTION")
	;
	
	public String val;
	
	private MapKeyApiEnum(String val) {
		this.val = val;
	}
}
