package com.keysoft.pigfarm.controller;

import java.util.Locale;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.validation.Valid;

import org.springframework.stereotype.Controller;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.servlet.ModelAndView;

import com.keysoft.pigfarm.production.dto.PigReleaseDto;

import lombok.extern.slf4j.Slf4j;

/**
 * Generated by Speed Generator
 * 
 * @author <a href="mailto:ngtrungkien@gmail.com">Kien Nguyen</a>
 */
 @Slf4j
@Controller
public class PigReleaseController extends BaseController {

    @GetMapping("/pigRelease/list")
    public ModelAndView list(HttpServletRequest request) throws Exception {
    	log.debug("entering 'list' method...");

        //modelAndView.addObject("pigReleases", pigReleaseManager.gets());

        return new ModelAndView("pigrelease-list");
    }
    
    @PostMapping("/pigRelease/list")
    public ModelAndView search(@Valid PigReleaseDto criteria, BindingResult bindingResult){
    	log.debug("entering 'search' method...");
		ModelAndView modelAndView = new ModelAndView("pigRelease-list");
		//modelAndView.addObject("page", pigReleaseManager.gets(criteria));
		modelAndView.addObject("criteria", criteria);
        return modelAndView;
    }
    
    @ModelAttribute
    @GetMapping("/pigRelease/form")
    public ModelAndView show(@RequestParam (value="id", required=false) Long id) throws Exception {
    	log.debug("entering 'show' method...");
    
    	ModelAndView modelAndView = new ModelAndView("pigrelease-form");
        //modelAndView.addObject(pigReleaseManager.get(id));

		modelAndView.addObject("pigRelease", new PigReleaseDto());

        return modelAndView;
    }

    @PostMapping("/pigRelease/save")
    public String save(@Valid PigReleaseDto pigReleaseDto, BindingResult bindingResult, HttpServletRequest request, HttpServletResponse response) throws Exception {
        log.debug("entering 'save' method...");

        Locale locale = request.getLocale();
        String view = "pigrelease-form";
        
        if (bindingResult.hasErrors()) {
        	addError(request, bindingResult.getAllErrors().toString());
            return view;
        }

        //pigReleaseManager.save(pigReleaseDto);
        //addMessage(request, getText("pigRelease.updated", locale));
        view = "redirect:/pigRelease/list";

        return view;
    }
    
    @PostMapping("/pigRelease/sendData")
    public String sendData(@Valid PigReleaseDto pigReleaseDto, BindingResult bindingResult, HttpServletRequest request, HttpServletResponse response) throws Exception {
        log.debug("entering 'sendData' method...");

        Locale locale = request.getLocale();
        String view = "pigrelease-form";
        
        if (bindingResult.hasErrors()) {
        	addError(request, bindingResult.getAllErrors().toString());
            return view;
        }

        //pigReleaseManager.save(pigReleaseDto);
        //addMessage(request, getText("pigRelease.updated", locale));
        view = "redirect:/pigRelease/list";

        return view;
    }
    
}