package com.keysoft.pigfarm.controller;

import java.util.ArrayList;
import java.util.List;
import java.util.Locale;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.validation.Valid;

import org.springframework.stereotype.Controller;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.servlet.ModelAndView;

import com.keysoft.pigfarm.common.PigType;
import com.keysoft.pigfarm.production.dto.FinishedProductDto;

import lombok.extern.slf4j.Slf4j;

/**
 * Generated by Speed Generator
 * 
 * @author <a href="mailto:ngtrungkien@gmail.com">Kien Nguyen</a>
 */
 @Slf4j
@Controller
public class FinishedProductController extends BaseController {
    @GetMapping("/finishedProduct/list")
    public ModelAndView list(HttpServletRequest request, @RequestParam(value="code", required=true) String code) throws Exception {
    	log.debug("entering 'list' method...");
    	
		ModelAndView modelAndView = new ModelAndView("finishedproduct-list");
		FinishedProductDto criteria = new FinishedProductDto();
		criteria.setProcessOrderCode(code);

        return modelAndView;
    }
    
    @PostMapping("/finishedProduct/list")
    public ModelAndView search(@Valid FinishedProductDto criteria, BindingResult bindingResult){
    	log.debug("entering 'search' method...");
		ModelAndView modelAndView = new ModelAndView("finishedproduct-list");
		modelAndView.addObject("criteria", criteria);
        return modelAndView;
    }
    
    @ModelAttribute
    @GetMapping("/finishedProduct/form")
    public ModelAndView show(@RequestParam (value="id", required=false) Long id) throws Exception {
    	log.debug("entering 'show' method...");
    
    	ModelAndView modelAndView = new ModelAndView("finishedproduct-form");
    	List<String> pigTypes = new ArrayList<>();
    	pigTypes.add(PigType.BA_MAU.value);
    	pigTypes.add(PigType.HAI_MAU.value);
    	pigTypes.add(PigType.HAU_BI.value);
    	modelAndView.addObject("pigTypes",pigTypes );
		modelAndView.addObject("finishedProduct", new FinishedProductDto());

        return modelAndView;
    }

    @PostMapping("/finishedProduct/save")
    public String save(FinishedProductDto finishedProductDto, BindingResult bindingResult, HttpServletRequest request, HttpServletResponse response) throws Exception {
        log.debug("entering 'save' method...");

        Locale locale = request.getLocale();
        String view = "finishedproduct-form";
        
        if (bindingResult.hasErrors()) {
        	addError(request, bindingResult.getAllErrors().toString());
            return view;
        }

        view = "redirect:/finishedProduct/list";

        return view;
    }
    
    @PostMapping("/finishedProduct/sendData")
    public String sendData(@Valid FinishedProductDto finishedProductDto, BindingResult bindingResult, HttpServletRequest request, HttpServletResponse response) throws Exception {
        log.debug("entering 'sendData' method...");

        Locale locale = request.getLocale();
        String view = "finishedproduct-form";
        
        if (bindingResult.hasErrors()) {
        	addError(request, bindingResult.getAllErrors().toString());
            return view;
        }

        view = "redirect:/finishedProduct/list";

        return view;
    }
    
}