package com.keysoft.pigfarm.controller;

import java.util.Locale;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.validation.Valid;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.servlet.ModelAndView;

import com.keysoft.pigfarm.manager.QuotaManager;
import com.keysoft.pigfarm.production.dto.QuotaDto;

import lombok.extern.slf4j.Slf4j;

/**
 * Generated by Speed Generator
 * 
 * @author <a href="mailto:ngtrungkien@gmail.com">Kien Nguyen</a>
 */
 @Slf4j
@Controller
public class QuotaController extends BaseController {

	@Autowired
    private QuotaManager quotaManager;

    @GetMapping("/quota/list")
    public ModelAndView list(HttpServletRequest request) throws Exception {
    	log.debug("entering 'list' method...");

        //modelAndView.addObject("quotas", quotaManager.gets());

        return new ModelAndView("quota-list");
    }
    
    @PostMapping("/quota/list")
    public ModelAndView search(@Valid QuotaDto criteria, BindingResult bindingResult){
    	log.debug("entering 'search' method...");
		ModelAndView modelAndView = new ModelAndView("quota-list");
		//modelAndView.addObject("page", quotaManager.gets(criteria));
		modelAndView.addObject("criteria", criteria);
        return modelAndView;
    }
    
    @ModelAttribute
    @GetMapping("/quota/form")
    public ModelAndView show(@RequestParam (value="id", required=false) Long id) throws Exception {
    	log.debug("entering 'show' method...");
    
    	ModelAndView modelAndView = new ModelAndView("quota-form");
        //modelAndView.addObject(quotaManager.get(id));

		modelAndView.addObject("quota", new QuotaDto());

        return modelAndView;
    }

    @PostMapping("/quota/save")
    public String save(QuotaDto quotaDto, BindingResult bindingResult, HttpServletRequest request, HttpServletResponse response) throws Exception {
        log.debug("entering 'save' method...");

        Locale locale = request.getLocale();
        String view = "quota-form";
        
        if (bindingResult.hasErrors()) {
        	addError(request, bindingResult.getAllErrors().toString());
            return view;
        }

        //quotaManager.save(quotaDto);
        addMessage(request, getText("quota.updated", locale));
        view = "redirect:/quota/list";

        return view;
    }
    
}