package com.keysoft.pigfarm.controller;

import java.util.Locale;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.validation.Valid;
import javax.validation.constraints.NotNull;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.servlet.ModelAndView;

import com.keysoft.pigfarm.manager.RoleManager;
import com.keysoft.pigfarm.master.dto.RoleDto;

import lombok.extern.slf4j.Slf4j;

/**
 * Generated by Speed Generator
 * 
 * @author <a href="mailto:ngtrungkien@gmail.com">Kien Nguyen</a>
 */
@Slf4j
@Controller
public class RoleController extends BaseController  {

    private RoleManager roleManager;

    
	@Autowired
    public void setRoleManager(RoleManager roleManager) {
        this.roleManager = roleManager;
    }

    
	@GetMapping("/role/list")
    public ModelAndView list(HttpServletRequest request) throws Exception {
    	log.debug("entering 'list' method...");
    	
		ModelAndView modelAndView = new ModelAndView("role-list");
		modelAndView.addObject("roles", roleManager.gets());

        return modelAndView;
    }
    
    
	@ModelAttribute
    @GetMapping("/role/edit/{id}")
    public ModelAndView show(@PathVariable ("id") @NotNull Long id) throws Exception {
    	log.debug("entering 'show' method...");
    
    	ModelAndView modelAndView = new ModelAndView("role-form");
        modelAndView.addObject(roleManager.get(id));

        return modelAndView;
    }

    
	@PostMapping("/role/save")
    public String save(@Valid RoleDto roleDto, BindingResult bindingResult, HttpServletRequest request, HttpServletResponse response) throws Exception {
        log.debug("entering 'save' method...");

        Locale locale = request.getLocale();
        String view = "role-form";
        
        if (bindingResult.hasErrors()) {
        	addError(request, bindingResult.getAllErrors().toString());
            return view;
        }

        roleManager.save(roleDto);
        addMessage(request, getText("role.updated", locale));
        view = "redirect:/role/list";

        return view;
    }
    
}