package com.keysoft.pigfarm.controller;

import java.util.Locale;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.validation.Valid;

import org.springframework.stereotype.Controller;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.servlet.ModelAndView;

import com.keysoft.pigfarm.production.dto.StockBalanceDto;

import lombok.extern.slf4j.Slf4j;

/**
 * Generated by Speed Generator
 * 
 * @author <a href="mailto:ngtrungkien@gmail.com">Kien Nguyen</a>
 */
 @Slf4j
@Controller
public class StockBalanceController extends BaseController {

    @GetMapping("/stockBalance/list")
    public ModelAndView list(HttpServletRequest request) throws Exception {
    	log.debug("entering 'list' method...");

        //modelAndView.addObject("stockBalances", stockBalanceManager.gets());

        return new ModelAndView("stockBalance-list");
    }
    
    @PostMapping("/stockBalance/list")
    public ModelAndView search(@Valid StockBalanceDto criteria, BindingResult bindingResult){
    	log.debug("entering 'search' method...");
		ModelAndView modelAndView = new ModelAndView("stockBalance-list");
		//modelAndView.addObject("page", stockBalanceManager.gets(criteria));
		modelAndView.addObject("criteria", criteria);
        return modelAndView;
    }
    
    @ModelAttribute
    @GetMapping("/stockBalance/form")
    public ModelAndView show(@RequestParam (value="id", required=false) Long id) throws Exception {
    	log.debug("entering 'show' method...");
    
    	ModelAndView modelAndView = new ModelAndView("stockBalance-form");
        //modelAndView.addObject(stockBalanceManager.get(id));

		modelAndView.addObject("stockBalance", new StockBalanceDto());

        return modelAndView;
    }

    @PostMapping("/stockBalance/save")
    public String save(StockBalanceDto stockBalanceDto, BindingResult bindingResult, HttpServletRequest request, HttpServletResponse response) throws Exception {
        log.debug("entering 'save' method...");

        Locale locale = request.getLocale();
        String view = "stockBalance-form";
        
        if (bindingResult.hasErrors()) {
        	addError(request, bindingResult.getAllErrors().toString());
            return view;
        }

        //stockBalanceManager.save(stockBalanceDto);
        addMessage(request, getText("stockBalance.updated", locale));
        view = "redirect:/stockBalance/list";

        return view;
    }
    
}