package com.keysoft.pigfarm.controller;

import java.time.LocalDate;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;

import javax.servlet.http.HttpServletRequest;
import javax.validation.Valid;

import org.apache.commons.lang3.StringUtils;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.servlet.ModelAndView;

import com.keysoft.pigfarm.common.DatePatternEnum;
import com.keysoft.pigfarm.helper.DateTimeHelper;
import com.keysoft.pigfarm.manager.StockCountManager;
import com.keysoft.pigfarm.production.dto.MaterialDetailDto;
import com.keysoft.pigfarm.production.dto.SearchDto;
import com.keysoft.pigfarm.production.dto.StockCountDto;

import lombok.extern.slf4j.Slf4j;

/**
 * Generated by Speed Generator
 * 
 * @author <a href="mailto:ngtrungkien@gmail.com">Kien Nguyen</a>
 */
@Slf4j
@Controller
public class StockCountController extends BaseController {

	@Autowired
    private StockCountManager stockCountManager;
	
	Map<String, SearchDto> userSearchs = new HashMap<>();

    @GetMapping("/stockCount/list")
    public ModelAndView list(HttpServletRequest request) throws Exception {
    	log.debug("ENTERING 'LIST STOCK_COUNT' METHOD...");
    	String userName = request.getUserPrincipal().getName();
		String url = request.getRequestURI();
		if(userSearchs.containsKey(userName)) {
			SearchDto searchDto = userSearchs.get(userName);
			String lastUrl = searchDto.getLatestUrl();
			
			if(lastUrl.equals(url) && searchDto.getSearchStockCount() != null) {
				return search(searchDto.getSearchStockCount(), request);
			}
		}
		
		ModelAndView modelAndView = new ModelAndView("stock-count-list");
		StockCountDto criteria = new StockCountDto();
		criteria.setLatest(true);
		criteria.setSize(appProperties.getDefaultPageSize());
    	criteria.setPage(appProperties.getDefaultPage());
		modelAndView.addObject("page", stockCountManager.gets(criteria));
		modelAndView.addObject("criteria", criteria);
        return modelAndView;
    }
    
    @PostMapping("/stockCount/list")
    public ModelAndView search(@Valid StockCountDto criteria, HttpServletRequest request){
    	log.debug("ENTERING 'SEARCH STOCK_COUNT' METHOD...");
		ModelAndView modelAndView = new ModelAndView("stock-count-list");
		if(criteria != null && criteria.getSize() == null){
			criteria.setSize(appProperties.getDefaultPageSize());
	    	criteria.setPage(appProperties.getDefaultPage());
	    }
		
		if(StringUtils.isNotBlank(criteria.getPostingDateSearch())) {
			LocalDate syncDate = DateTimeHelper.toLocalDate(criteria.getPostingDateSearch(), DatePatternEnum.DD_MM_YYYY_2.pattern);
			criteria.setPostingDate(syncDate);
		}
		
		modelAndView.addObject("page", stockCountManager.gets(criteria));
		modelAndView.addObject("criteria", criteria);
		
		String userName = request.getUserPrincipal().getName();
		String url = request.getRequestURI();
		if(userSearchs.containsKey(userName)) {
			SearchDto searchDto = userSearchs.get(userName);
			searchDto.setSearchStockCount(criteria);
			searchDto.setLatestUrl(url);
			userSearchs.put(userName, searchDto);
		} else {
			SearchDto searchDto = new SearchDto();
			searchDto.setSearchStockCount(criteria);
			searchDto.setLatestUrl(url);
			userSearchs.put(userName, searchDto);
		}
		
        return modelAndView;
    }
    
    @ModelAttribute
    @GetMapping("/stockCount/form")
    public ModelAndView show(@RequestParam(value="id", required=false) Long id, HttpServletRequest request) throws Exception {
    	log.debug("ENTERING 'SHOW STOCK_COUNT' METHOD...");
    	Locale locale = request.getLocale();
    	ModelAndView modelAndView = new ModelAndView("stock-count-form");
    	StockCountDto stockCount = new StockCountDto();
    	List<MaterialDetailDto> materialDetails = new ArrayList<>();
    	if(id != null) {
    		stockCount = stockCountManager.get(id);
    		if(stockCount == null) {
        		addError(request, getText("data.notfound", locale));
				return new ModelAndView("redirect:/stockCount/list");
        	}
    		
    		materialDetails = stockCount.getMaterialDetails();
    	} else {
    		modelAndView.setViewName("redirect:/stockCount/list");
    		addError(request, getText("instock.notfound", request.getLocale()));
    	}
    	modelAndView.addObject("materialDetails", materialDetails);
        modelAndView.addObject("stockCount", stockCount);
        return modelAndView;
    }
}