package com.keysoft.pigfarm.manager;

import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.core.ParameterizedTypeReference;
import org.springframework.http.HttpMethod;
import org.springframework.http.ResponseEntity;
import org.springframework.stereotype.Service;

import com.keysoft.pigfarm.config.ServiceProperties;
import com.keysoft.pigfarm.constant.ApiEnum;
import com.keysoft.pigfarm.master.dto.RoleDto;
import com.keysoft.pigfarm.util.RestHelper;

import lombok.extern.slf4j.Slf4j;

/**
 * Generated by Speed Generator
 * 
 * @author <a href="mailto:ngtrungkien@gmail.com">Kien Nguyen</a>
 */
@Slf4j
@Service
public class RoleManager {
	
	@Autowired
	private RestHelper restHelper;
	
	@Autowired
	private ServiceProperties serviceProperties;
	
	public RoleDto get(Long id) {
		log.info("process=get-role, role_id={}", id);
		ResponseEntity<?> responseEntity = restHelper.send(serviceProperties.getPaths().get(ApiEnum.PATH_ROLE_GET.val),HttpMethod.GET,RoleDto.class, id);
		return (RoleDto) responseEntity.getBody();
	}
	
	@SuppressWarnings("unchecked")
	public List<RoleDto> gets() {
		log.info("process=get-roles");
		ResponseEntity<?> response = restHelper.send(serviceProperties.getPaths().get(ApiEnum.PATH_ROLE_GETS.val), HttpMethod.GET, new ParameterizedTypeReference<List<RoleDto>>(){});
		return (List<RoleDto>) response.getBody();
	}
	
	public RoleDto save(RoleDto roleDto) {
		log.info("process=save-role, role={}", roleDto);
		return null;
	}
	
	// get Roles
	public List<RoleDto> getRoles(Long groupId){
		log.info("process=get-roles, group_id={}", groupId);
		return null;
	}
	
	@SuppressWarnings("unchecked")
	public List<RoleDto> getRolesByGroupName(String groupName) {
		ResponseEntity<?> response = restHelper.send(
				serviceProperties.getPaths().get(ApiEnum.PATH_ROLE_BY_GROUP_NAME_GET.val)
				, HttpMethod.GET
				, new ParameterizedTypeReference<List<RoleDto>>() {}
				, groupName);
		return (List<RoleDto>) response.getBody();
	}
}