package com.keysoft.pigfarm.production.dto;

import java.util.List;
import java.util.Map;

import com.keysoft.pigfarm.common.BaseDto;

import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.experimental.SuperBuilder;

/**
 * Generated by Speed Generator
 * 
 * @author <a href="mailto:ngtrungkien@gmail.com">Kien Nguyen</a>
 */
@Data
@SuperBuilder
@NoArgsConstructor
@EqualsAndHashCode(callSuper = false)
public class FarmDto extends BaseDto {
  	private Long id;
  	private String code;
  	private String name;
  	private String type;
  	private String allowPosting;
  	private String wbsId;
  	private String wbsCode;
  	private String wbsDesc;
  	private Map<String, Object> attribute;
  	private List<FarmUserDto> farmUsers;
  	private PlantDto plant;
	private String plantCode;
  	private String status;
  	private String address;
  	private boolean porkerFarm;
	private String fax;
	private String phoneNumber;

  	private String username;
  	private List<BarnDto> barns ;
  	private Integer TotalPigRetained ;
  	private Integer TotalPigDead;

}