package com.keysoft.pigfarm.production.dto;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.List;
import java.util.Map;

import com.keysoft.pigfarm.common.BaseDto;

import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.experimental.SuperBuilder;

/**
 * Generated by Speed Generator
 * 
 * @author <a href="mailto:ngtrungkien@gmail.com">Kien Nguyen</a>
 */
@Data
@SuperBuilder
@NoArgsConstructor
@EqualsAndHashCode(callSuper = false)
public class GoodsIssueDto extends BaseDto{
  	private Long id;
  	private String fromStockCode;
  	private String fromStockName;
  	private String toStockCode;
  	private String toStockName;
  	private String grCode;
  	private String doCode;
  	private String transCode;
  	private String barnCode;
  	private String type;
  	private String processOrderCode;
  	private Long processOrderId;
  	private String customer;
  	private String customerReceiver;
  	private LocalDate postingDate;
  	private Map<String, Object> content;
  	private String createdPerson;
  	private String receivedPerson;
  	private String storekeeper;
  	private String status;
  	private String createdBy;
  	private LocalDateTime createdDate;
  	private String modifiedBy;
  	private LocalDateTime modifiedDate;
  	private Long goodsRequisitionId;
  	private StockDto stock;
  	private String poCode;
	private String prCode;
	private String customerName;
  	private String movementType;
  	private String stockCode;
  	private String templateName;
  	private ProductionDto production;
  	private String stockName;
  	
  	private ProcessOrderDto processOrder;
  	private List<QuotaDto> lstQuota;
  	private String contentJson;
  	private BigDecimal weight;
  	private String username;
  	private String licensePlate;
  	private String transType;
  	
	private List<String> farmCodes;
	
	private String displayPostingDate;
  	public String getDisplayPostingDate() {
  		if (postingDate != null) {
  			return DateTimeFormatter.ofPattern("dd-MM-yyyy").format(postingDate);  
  		} else {
  			return null;
  		}
  	}
  	
  	// for searching postingDate 
  	private String  postingDateSearch;
  	private List<LocalDate> postingDateSearchPeriod;
  	private LocalDate startDate;
  	private LocalDate endDate;
	private String searchFromDate;
	private String searchToDate;
  	private List<MaterialDto> materials;
	private List<MaterialDetailDto> materialDetails;
  	// for report
  	private String period;
  	private String action;
  	private String farmCodeSelected;
  	private Boolean checkInsertTool;
  	private Boolean markDel;
  	private String processOrderStatus;
}