package com.keysoft.pigfarm.production.dto;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.List;
import java.util.Map;

import com.keysoft.pigfarm.common.BaseDto;

import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.experimental.SuperBuilder;

/**
 * Generated by Speed Generator
 * 
 * @author <a href="mailto:ngtrungkien@gmail.com">Kien Nguyen</a>
 */
@Data
@SuperBuilder
@NoArgsConstructor
@EqualsAndHashCode(callSuper = false)
public class GoodsReceiptDto extends BaseDto{
  	private Long id;
  	private String fromStockCode;
  	private String fromStockName;
  	private String toStockCode;
  	private String toStockName;
  	private String transCode;
  	private String type;
  	private String prCode;
  	private String poCode;
  	private String grCode;
  	private String customer;
  	private LocalDate postingDate;
  	private Map<String, Object> content;
  	private String createdPerson;
  	private String receivedPerson;
  	private String storekeeper;
  	private String status;
  	private String createdBy;
  	private LocalDateTime createdDate;
  	private String modifiedBy;
  	private LocalDateTime modifiedDate;
  	private ProductionDto production;
  	private Long goodsRequisitionId;
  	private StockDto stock;
  	private String username;
  	private String doCode;
	private String vendorName;
	private String vendor;
	private String transType;
	private String movementType;
	private String stockCode;
	private String stockName;
	private String templateName;
  	
  	private String displayPostingDate;
  	public String getDisplayPostingDate() {
  		if (postingDate != null) {
  			return DateTimeFormatter.ofPattern("dd-MM-yyyy").format(postingDate);  
  		} else {
  			return null;
  		}
  	}
  	
  	private String displayCreatedDate;
  	public String getDisplayCreatedDate() {
  		if (createdDate != null) {
  			return DateTimeFormatter.ofPattern("dd-MM-yyyy").format(createdDate);  
  		} else {
  			return null;
  		}
  	}
  	
  	private List<MaterialDto> materials;
  	private List<MaterialDetailDto> materialDetails;
  	private String  postingDateSearch;
  	private LocalDate startDate;
  	private LocalDate endDate;

	private String searchFromDate;
	private String searchToDate;
  	
  	private boolean markDel;
}