package com.keysoft.pigfarm.production.dto;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.List;
import java.util.Map;

import com.keysoft.pigfarm.common.BaseDto;

import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.experimental.SuperBuilder;

/**
 * Generated by Speed Generator
 * 
 * @author <a href="mailto:ngtrungkien@gmail.com">Kien Nguyen</a>
 */
@Data
@SuperBuilder
@NoArgsConstructor
@EqualsAndHashCode(callSuper = false)
public class GoodsRequisitionDto extends BaseDto{
  	private Long id;
  	private String fromStockCode;
  	private String fromStockName;
  	private String toStockCode;
  	private String toStockName;
  	private String grCode;
  	private String prCode;
  	private String type;
  	private String customer;
  	private LocalDate postingDate;
  	private Map<String, Object> content;
  	private String status;
  	private String createdBy;
  	private LocalDateTime createdDate;
  	private String modifiedBy;
  	private LocalDateTime modifiedDate;
  	private String prGroupCode;
  	private String prType;
  	private String requisitioner;
  	private String plant;
  	private String movementType;
  	private String doCode;
   	private String poCode;
   	private String costCenter;
   	private String reason;
   	private BigDecimal totalRetained;
   	private StockDto stock;
   	private String username;
   	private String createdDateTime;
   	private String customerName;
  	private String vendor;
   	private String vendorName;
   	private String transType;
  	private String transCode;
  	private String stockCode;
  	private String stockName;
  	private List<MaterialDto> materials;
  	private boolean checkRetained;
  	
  	private String displayCreatedDate;
  	private List<MaterialDetailDto> materialDetails;
  	public String getDisplayCreatedDate() {
  		if (createdDate != null) {
  			return DateTimeFormatter.ofPattern("dd-MM-yyyy").format(createdDate);  
  		} else {
  			return null;
  		}
  	}
  	
  	private String displayPostingDate;
  	public String getDisplayPostingDate() {
  		if (postingDate != null) {
  			return DateTimeFormatter.ofPattern("dd-MM-yyyy").format(postingDate);  
  		} else {
  			return null;
  		}
  	}
}