package com.keysoft.pigfarm.production.dto;

import java.time.LocalDateTime;
import java.util.Map;

import lombok.Data;

/**
 * Generated by Speed Generator
 * 
 * @author <a href="mailto:ngtrungkien@gmail.com">Kien Nguyen</a>
 */
@Data
public class PigProfileDto {
  	private Long id;
  	private String pigIdentifier;
  	private Map<String, Object> content;
  	private String createdBy;
  	private LocalDateTime createdDate;
  	private String modifiedBy;
  	private LocalDateTime modifiedDate;
}