package com.keysoft.pigfarm.production.dto;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.List;
import java.util.Map;

import com.keysoft.pigfarm.common.BaseDto;

import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.experimental.SuperBuilder;

/**
 * Generated by Speed Generator
 * 
 * @author <a href="mailto:ngtrungkien@gmail.com">Kien Nguyen</a>
 */
@Data
@SuperBuilder
@NoArgsConstructor
@EqualsAndHashCode(callSuper = false)
public class PurchaseRequisitionDto extends BaseDto{
  	private Long id;
 	private String transCode;
  	private String stockCode;
  	private String prGroupCode;
  	private String prCode;
  	private String prType;
  	private LocalDate deliveryDate;
  	private String requisitioner;
  	private Map<String, Object> content;
  	private String plant;
  	private String type;
  	private String status;
  	private String createdBy;
  	private LocalDateTime createdDate;
  	private String modifiedBy;
  	private LocalDateTime modifiedDate;
  	private String contentJson;
  	private StockDto stock;
  	
  	private List<MaterialDto> materials;
  	private String username;
  	private String stockName;
  	
  	private String resultCode;
  	private String resultMessage;
  	private String templateName;
  	private String purchasingGroup;
  	
  	
  	private String displayDeliveryDate;
  	public String getDisplayDeliveryDate() {
  		if (deliveryDate != null) {
  			return DateTimeFormatter.ofPattern("dd-MM-yyyy").format(deliveryDate);  
  		} else {
  			return null;
  		}
  	}
  	
  	private String displayCreatedDate;
  	public String getDisplayCreatedDate() {
  		if (createdDate != null) {
  			return DateTimeFormatter.ofPattern("dd-MM-yyyy").format(createdDate);  
  		} else {
  			return null;
  		}
  	}
  	private List<MaterialDetailDto> materialDetails;
  	private List<MaterialDetailDto> materialDetailTypeWeeks;
  	private List<MaterialDetailDto> materialDetailTypeMonths;
}