package com.keysoft.pigfarm.production.dto;

import java.time.LocalDateTime;
import java.util.Map;

import lombok.Data;

/**
 * Generated by Speed Generator
 * 
 * @author <a href="mailto:ngtrungkien@gmail.com">Kien Nguyen</a>
 */
@Data
public class StockBalanceDto {
  	private Long id;
  	private String stockCode;
  	private Map<String, Object> content;
  	private String eventCode;
  	private String eventType;
  	private boolean latest;
  	private LocalDateTime createdDate;
  	private String createdBy;
}