package com.keysoft.pigfarm.production.dto;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.List;
import java.util.Map;

import com.keysoft.pigfarm.common.BaseDto;
import com.keysoft.pigfarm.common.DatePatternEnum;

import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.experimental.SuperBuilder;

/**
 * Generated by Speed Generator
 * 
 * @author <a href="mailto:ngtrungkien@gmail.com">Kien Nguyen</a>
 */
@Data
@SuperBuilder
@NoArgsConstructor
@EqualsAndHashCode(callSuper = false)
public class StockCountDto extends BaseDto{
  	private Long id;
  	private String stockCode;
  	private LocalDate postingDate;
  	private Map<String, Object> content;
  	private boolean latest;
  	private String createdBy;
  	private LocalDateTime createdDate;
  	private String modifiedBy;
  	private LocalDateTime modifiedDate;
  	private StockDto stock;
  	private String transCode;
  	
  	private String username;
  	private List<MaterialDetailDto> materialDetails;
  	
  	private String displayPostingDate;
  	public String getDisplayPostingDate() {
  		if (postingDate != null) {
  			return DateTimeFormatter.ofPattern("dd-MM-yyyy").format(postingDate);  
  		} else {
  			return null;
  		}
  	}
  	
  	private String displayCreatedDate;
  	public String getDisplayCreatedDate() {
  		if (createdDate != null) {
  			return DateTimeFormatter.ofPattern(DatePatternEnum.DD_MM_YYYY__HH_MM_SS.pattern).format(createdDate);  
  		} else {
  			return null;
  		}
  	}
  	
  	private String stockName;
  	private String postingDateSearch;
}