package com.keysoft.pigfarm.production.dto;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.List;
import java.util.Map;

import com.keysoft.pigfarm.common.BaseDto;
import com.keysoft.pigfarm.common.SymbolEnum;

import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.experimental.SuperBuilder;

/**
 * Generated by Speed Generator
 * 
 * @author <a href="mailto:ngtrungkien@gmail.com">Kien Nguyen</a>
 */
@Data
@SuperBuilder
@NoArgsConstructor
@EqualsAndHashCode(callSuper = false)
public class EventDto extends BaseDto {
  	private Long id;
  	private String code;
  	private String type;
  	private Map<String, Object> content;
  	private String createdBy;
  	private LocalDateTime createdDate;
  	private String modifiedBy;
  	private LocalDateTime modifiedDate;
  	private String processOrderCode;
  	private String status;
	private ProductionDto production;
  	private String transCode;
	
//	private String pigType;
	private BigDecimal quantity;
	private BigDecimal weight;
	private String reason;
	private String materialCode;
	private List<String> types;
	private String barnCode;
	private LocalDate postingDate;
	
	private String displayCreatedDate;
  	public String getDisplayCreatedDate() {
  		if (createdDate != null) {
  			return DateTimeFormatter.ofPattern("dd-MM-yyyy").format(createdDate);  
  		} else {
  			return null;
  		}
  	}
  	
  	private String displayPostingDate;
  	public String getDisplayPostingDate() {
  		if (postingDate != null) {
  			return DateTimeFormatter.ofPattern("dd-MM-yyyy").format(postingDate);  
  		} else {
  			return null;
  		}
  	}
  	
  	private PigCullingDto pigCulling;
  	private WeightNoteDto weightNote;
  	private PigProductionDto pigProd;
  	
  	private LocalDateTime searchFrom;
  	private LocalDateTime searchTo;
  	private String displaySearchFromDate;
  	private String displaySearchToDate;
  	private List<MaterialDetailDto> materialDetails;
  	
  	// for report
  	private LocalDate postingFrom;
  	private LocalDate postingTo;
  	private String stage;
  	private String username;
  	private List<String> farmCodes;			//tìm kiếm theo nhiều mã trại
	private List<String> barnCodes;			//tìm kiếm theo nhiều mã chuồng
	private String barnCodeStr;
	private List<String> weightRange;	 	//tìm kiếm theo biểu cân
	private String weightRangeStr;
	private List<String> processOrderCodes;	//tìn kiếm theo lệnh sx
	private String farmCodesStr;
  	public String getFarmCodesStr() {
  		if (farmCodes != null) {
  			  StringBuilder temp = new StringBuilder();
  			  for(String s : farmCodes) {
  				temp = temp.append(s).append(SymbolEnum.COMMA.val);
  			  }
  			  return temp.toString();
  		} else {
  			return null;
  		}
  	}
  	public String getBarnCodeStr() {
  		if (barnCodes != null) {
  			  StringBuilder temp = new StringBuilder();
  			  for(String b : barnCodes) {
  				temp = temp.append(b).append(SymbolEnum.COMMA.val);
  			  }
  			  return temp.toString();
  		} else {
  			return null;
  		}
  	}
  	
  	public String getWeightRangeStr() {
  		if (weightRange != null) {
  			  StringBuilder temp = new StringBuilder();
  			  for(String r : weightRange) {
  				temp = temp.append(r).append(SymbolEnum.COMMA.val);
  			  }
  			  return temp.toString();
  		} else {
  			return null;
  		}
  	}
	
}