package com.keysoft.pigfarm.production.dto;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.List;
import java.util.Map;

import com.keysoft.pigfarm.common.BaseDto;

import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.experimental.SuperBuilder;

/**
 * Generated by Speed Generator
 * 
 * @author <a href="mailto:ngtrungkien@gmail.com">Kien Nguyen</a>
 */
@Data
@SuperBuilder
@NoArgsConstructor
@EqualsAndHashCode(callSuper = false)
public class ProductionDto extends BaseDto{
  	private Long id;
  	private String processOrderCode;
  	private String code;
  	private Integer feedDay;
  	private LocalDate feedDate;
  	private Integer feedWeek;
  	private LocalDate feedWeekStartDate;
  	private LocalDate feedWeekToDate;
  	private Integer totalPig;
  	private Integer totalPigRetained;
  	private Integer totalPigDead;
  	private Integer totalPigCulling;
  	private Integer totalPigRelease;
  	private Map<String, Object> moreInfo;
  	private String createdBy;
  	private LocalDateTime createdDate;
  	private String modifiedBy;
  	private LocalDateTime modifiedDate;
  	private boolean latest;
  	private List<EventDto> events;
  	private List<GoodsReceiptDto> goodsReceipts;
  	private LocalDate realStartDate;
  	private LocalDateTime startDate;
  	private LocalDateTime endDate;
  	private LocalDate postingDate;
  	private String searchPostingDate;
}