package com.keysoft.pigfarm.master.dto;

import com.keysoft.pigfarm.common.BaseDto;

import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.experimental.SuperBuilder;

/**
 * Generated by Speed Generator
 * 
 * @author <a href="mailto:ngtrungkien@gmail.com">Kien Nguyen</a>
 */
@Data
@SuperBuilder
@NoArgsConstructor
@EqualsAndHashCode(callSuper = false)
public class TenantDto extends BaseDto {
  	private Long id;
  	private String code;
  	private String name;
  	private String application;
  	private String adminUsername;
  	private String adminPassword;
}